### ISSUE TITLE
Still rendition types not working

### ISSUE THREAD

**Issue by Vaberer** [Giphy/giphy-ios-sdk-ui-example#113]
When setting `rendtitionType` to any value of `still` types, `GiphyViewController` shows blank images. Since documentation and sdk include `still` rendition types, it's a bug and let's keep track of the progress of this issue.
I'm happy to assist and help to debug this issue.

**Comment by Vaberer** [comment]
Any updates regarding this issue? Looks, the URL is correct https://media4.giphy.com/media/l378ifi3c4pTHpXUY/giphy_s.gif?cid=12faed9dapl055s12r0a04jg48087un16esdxwsxl38ucu90&rid=giphy_s.gif but the sdk doesn't show the images.
I also found that
`media.url(rendition: .originalStill, fileType: .gif)`
or 
media.url(rendition: .originalStill, fileType: .webp)
don't work, too.

**Comment by jerrodputman** [comment]
The issue seems to occur in `GiphyYYImageView` due to UIKit changes. A similar issue is described for SDWebImage here: https://github.com/SDWebImage/SDWebImage/issues/3040

Downloading the `still` through the `GPHCache.shared.downloadAsset` method and looking at the image in the debugger, the image is downloaded correctly. However, assigning that image to `GiphyYYImageView` produces an invisible view.

I discovered that if you set the image to `animatedImages`, the issue can be worked around:

`imageView.animatedImages = [gifStillImage]`

Unfortunately, this can't be fixed in `GiphyViewController` unless the Giphy team fixes it.

**Comment by ifabijanovic** [comment]
Can someone from the Giphy team respond here? The fix seems simple enough and this is a blocker for us upgrading to Xcode 12

**Comment by cgmaier** [comment]
hey there, sorry for the silence. the fix @jerrodputman has suggested will be included in a new release later today.

**Comment by ifabijanovic** [comment]
Wait are you thinking on the lines of using the `animatedImages` workaround or the fix that was made in SDWebImage (https://github.com/SDWebImage/SDWebImage/pull/3043)?

**Comment by cgmaier** [comment]
@ifabijanovic yup - any concerns with that?

**Comment by ifabijanovic** [comment]
Our concrete problem is with using `GPHMediaView` essentially as a `UIImageView` in some cases - setting the `image` property does not actually display that image when built with Xcode 12 (when inspected in the design debugger the image layer is there but it is invisible). We do that in some places which can either show a local image, remote image or a gif. The suggestion of just assigning the loaded asset to `animatedImages` will not address this problem, and using that workaround for us is also not feasible `animationImages` are not tinted for example.

Is it possible to fix the underlying issue in the actual `GPHMediaView` or `GiphyYYAnimatedImageView`, similar to how it was done in `SDWebImage` fix? My guess is that it's a similar problem

**Comment by cgmaier** [comment]
hi - this should be properly addressed in `2.0.8`
