### ISSUE TITLE
Set status bar appearance

### ISSUE THREAD

**Issue by h36ahmed** [Giphy/giphy-ios-sdk-ui-example#15]
My app has certain screens on older phones like iPhone 6/7 where I have to hide status bar for increasing canvas space. When I present giphy it shows status bar on those screens. Possible to add a configuration to override status bar appearance?

**Comment by cgmaier** [comment]
interesting, another good catch. 

rather than another setting, I think it may make more sense to mark the `GiphyViewController` with the `open` modifier rather than just `public`, so that developers can subclass it and override the necessary methods to achieve status bar behavior, as well as other things. 

i'll get back to you soon !

**Comment by h36ahmed** [comment]
Awesome, that will work well

**Comment by h36ahmed** [comment]
yup i checked the example. You have done it correctly. i have fixed it on my end by making navigation controller hide the status bar.
