### ISSUE TITLE
Giphy Core SDK

### ISSUE THREAD

**Issue by codeplotter** [Giphy/giphy-ios-sdk-ui-example#43]
I am having a problem where I can't compile after installing the Giphy Core SDK pod.  I am using that SDK because in #41 I was told the full SDK would not work in keyboard extensions.  I am working on CapGenius and we want to integrate Giphy into our keyboard.  Here is the message I am getting:

<img width="723" alt="Screen Shot 2019-11-20 at 12 53 35 AM" src="https://user-images.githubusercontent.com/25725009/69215846-532cc480-0b30-11ea-9cfa-c1ab5dd2c317.png">

Here is the command I was told to use in my podfile:

  pod 'GiphyCore', :podspec => 'https://s3.amazonaws.com/sdk.mobile.giphy.com/SDK/1.0.1/GiphyCore.podspec'

**Comment by drewolbrich** [comment]
Try this:
```
pod update Giphy
```
Make sure you are using a newer version of the Giphy SDK, like 1.1.6, and not an older version, like 1.1.2.

**Comment by codeplotter** [comment]
I ran "pod update GiphyCore" but had no change.  Please note that I am not using the full Giphy SDK since this is a keyboard extension, as mentioned above. 

It looks like the command I was originally told to use is installing 1.0.1 of the GiphyCore SDK.  Is there a newer version of that?

**Comment by cgmaier** [comment]
hey @codeplotter really sorry about all the confusion! 

I believe someone from our team has been in touch with you, as the extension use case isn't covered by the UI SDK, and you have may been sent some out of date docs. I believe that's all been (hopefully) resolved or will be soon!

Because you're not going to be using the UI SDK going forward, please direct future questions / issues directly to our SDK team here: sdk@giphy.com : ) I'm going to go ahead and close this issue if that's alright !
