### ISSUE TITLE
Question For ExampleObjectiveC

### ISSUE THREAD

**Issue by JianwenYan** [Giphy/giphy-ios-sdk-ui-example#46]
I simplely add a previewView(GPHMediaView) to show after select, but it was no use after my selected.

```
 self.previewView = [[GPHMediaView alloc] initWithFrame:CGRectMake(0, 0, 300, 300)];
 [self.view addSubview:self.previewView];
```

```
- (void) didSelectMediaWithGiphyViewController:(GiphyViewController *)giphyViewController media:(GPHMedia *)media {
    [self.previewView setMedia:media rendition:GPHRenditionTypePreview shouldQueueOriginalRendition:NO];
}

```

**Comment by ancloid** [comment]
Same issue, media.images.original.width and media.images.original.height is 0
Why?

**Comment by cgmaier** [comment]
hey @JianwenYan sorry for the late reply on this. Were you able to find a working solution? 

I believe the issue might be with the `GPHRenditionTypePreview` setting. It's likely better to choose `GPHRenditionTypeOriginal` for a high resolution rendition of the GIF, or remove the parameter altogether to go with what is chosen in the grid, which is smaller (also beneficial because that image is already cached) 

@ancloid I've not experienced that issue with `original.width` and `original.height` dimensions - I'll keep an eye out for it! The `GPHMedia` property `aspectRatio` may be of use in similar contexts.
